
runtime: go
api_version: go1

skip_files:
- ^(.*/)?#.*#$
- .git
- artemlazarev.github.io.git

handlers:

- url: /assets/css
  static_dir: www/assets/css
- url: /assets/fonts
  static_dir: www/assets/fonts
- url: /assets/js
  static_dir: www/assets/js
- url: /images
  static_dir: www/images
- url: /
  static_files: www/index.html
  upload: www/index.html


- url: /shop/.*
  script: _go_app

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
