name: deploy on any Push event
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: pwd ; ls -la
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: upload to bucket
        run: gsutil cp -r www/* gs://artemlazarev.com
